### PR TITLE
Fix WRAM0 symbols returning bank 512 to BANK() expression in linker

### PR DESCRIPTION
**Pull request by PikalaxALT**

### CODE REVIEW

**Comment by Ben10do** [comment]
Careful – your newer commits are being added to this pull request…

**Comment by PikalaxALT** [comment]
That's the intention.

**Comment by Ben10do** [comment]
I think it's generally considered best to separate unrelated changes into separate PRs, but if you want to keep amending this one, I'd at least alter its title and/or description to indicate that it does more than fix the `BANK()` expression.

**Comment by bentley** [comment]
Separate pull requests, please.

**Comment by PikalaxALT** [comment]
Due to the assign refactor, this PR is obsolete.  I'll reapply the changes to the current link/assign and open new PRs.

**Pull request closed without merging**
