### PR TITLE
added "STR" assembler command

### PR DESCRIPTION
**Pull request by lr35902**
works like "DB" but also does null termination

### CODE REVIEW

**Comment by AntonioND** [comment]
Hmmm... This is useful and potentially bad at the same time, I think. On the one hand, it is really convenient to avoid writing ",0" every time you add a string. On the other hand, I don't know if it's a good practice to add all strings as ASCII on the gameboy... I do it in some cases, but I also have macros that convert ASCII strings into the indexes of my text font: https://github.com/AntonioND/bitcity/blob/master/source/text.inc#L65 (this would really benefit from the ELIF of this PR: https://github.com/bentley/rgbds/pull/23) The problem is that they are equally annoying to use, to be honest.

Also, how should it behave if you want to add control characters? Right now, nothing prevents the code from doing `DB "Hello",1," World",0`, would that work with STR?

**Comment by lr35902** [comment]
it optional, it's completely fine to keep on using "DB". when working with a ASCII tileset it's pretty convenient though.

as for your specific situation, what about creating something like a "STR2TILES" assembler function that takes a ASCII string and converts it using a (user supplied) mapping file? something like **rgbasm -m yourtiles.map** and **STR STR2TILES("foobar")**, it's a bit of coding but i guess it would yield exactly what you need/want.

yes, you can add as many control characters as you want
**DB "HelloWorld!",0**  yields the same result as
**STR "HelloWorld!"**
**DB "Hello",1," World",0**  yields the same result as
**STR "Hello",1," World"**
i wouldn't use "STR" for the latter one though.

**Comment by AntonioND** [comment]
> what about creating something like a "STR2TILES" assembler function that takes a ASCII string and converts it using a (user supplied) mapping file?

That's what I was thinking, but I don't know if there is a real need for this, specially since a game could potentially use 2 or more mappings for any reason...

Now that I think of it, there is the "charmap" API. I should take a look at it because it is potentially what I need instead of my macro. https://github.com/pret/pokered/blob/46a94c63fc287e7290502776d02648476bc44171/charmap.asm

Anyway, yeah, this PR could be useful.

**Comment by AntonioND** [comment]
Turns out my macro is useless as charmaps exist. Forget what I said...

**Pull request closed without merging**
